from cache import Cache


c = Cache(5)
c.set_replace_policy('lru')
c.read(1)
c.write(1, 'i')
c.write(2, 'p')
c.read(1)
# print(c.data)
c.write(3, 'mmm')
c.write(3, '33')
c.write(3, '3333')
c.write(4, 'aaa')
c.write(2,'bb')
c.write(8, '8')
c.write(10, '10')
# print(c.data)
print(c.RP)
# print(c.RP.access_contrl)
print(c.RP.lru())
print(c.RP)